default:
  app:
    name: Example MQTT API
    version: 1.0.12

  broker:


    mqtt:
      url: mqtt://localhost:1884
      topics: ["sensor/data"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true


development:

test:

staging:

production:

