// This file is auto-generated by @hey-api/openapi-ts

export type Todo = {
    id: number;
    title: string;
    completed: boolean;
};

export type NewTodo = {
    title: string;
    completed?: boolean;
};

export type GetTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type GetTodosResponses = {
    /**
     * A JSON array of todos
     */
    200: Array<Todo>;
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type CreateTodoData = {
    /**
     * The todo to be created
     */
    body: NewTodo;
    path?: never;
    query?: never;
    url: '/todos';
};

export type CreateTodoResponses = {
    /**
     * The created todo object
     */
    201: Todo;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type GetTodoByIdData = {
    body?: never;
    path: {
        /**
         * ID of the todo to operate on
         */
        todoId: number;
    };
    query?: never;
    url: '/todos/{todoId}';
};

export type GetTodoByIdErrors = {
    /**
     * Todo not found
     */
    404: unknown;
};

export type GetTodoByIdResponses = {
    /**
     * A single todo item
     */
    200: Todo;
};

export type GetTodoByIdResponse = GetTodoByIdResponses[keyof GetTodoByIdResponses];

export type UpdateTodoData = {
    /**
     * Updated todo information
     */
    body: Todo;
    path: {
        /**
         * ID of the todo to operate on
         */
        todoId: number;
    };
    query?: never;
    url: '/todos/{todoId}';
};

export type UpdateTodoErrors = {
    /**
     * Invalid input supplied
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type UpdateTodoResponses = {
    /**
     * The updated todo object
     */
    200: Todo;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:5000' | (string & {});
};